# Must only be called from a workflow_run in the context of the upstream repo
name: SonarCloud
on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        description: The full name of the repo in org/repo format
      head_branch:
        type: string
        required: true
        description: The name of the head branch
      # We cannot use ${{ github.sha }} here as for pull requests it'll be a simulated merge commit instead
      revision:
        type: string
        required: true
        description: The git revision with which this sonar run should be associated

      # Coverage specific parameters, assumes coverage reports live in a /coverage/ directory
      coverage_workflow_name:
        type: string
        required: false
        description: The name of the workflow which uploaded the `coverage` artifact, if any
      coverage_run_id:
        type: string
        required: false
        description: The run_id of the workflow which upload the coverage relevant to this run

      # PR specific parameters
      pr_id:
        type: string
        required: false
        description: The ID number of the PR if this workflow is being triggered due to one
      base_branch:
        type: string
        required: false
        description: The base branch of the PR if this workflow is being triggered due to one
    secrets:
      SONAR_TOKEN:
        required: true
jobs:
  sonarqube:
    name: 🩻 SonarQube
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: "🧮 Checkout code"
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }} # checkout commit that triggered this workflow
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: "🔍 Read package.json version"
        id: version
        uses: martinbeentjes/npm-get-version-action@main

      - name: "🩻 SonarCloud Scan"
        uses: matrix-org/sonarcloud-workflow-action@v1
        with:
          is_pr: ${{ github.event.workflow_run.event == 'pull_request' }}
          owner: ${{ github.event.workflow_run.head_repository.owner.login }}
          version: ${{ steps.version.outputs.current-version }}
          branch: ${{ github.event.workflow_run.head_branch }}
          revision: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.SONAR_TOKEN }}
          coverage_run_id: ${{ github.event.workflow_run.id }}
          coverage_workflow_name: tests.yml
          coverage_extract_path: coverage
